spring:
    application:
            name: PNC
    datasource:
        url: jdbc:mysql://localhost:3306/PNC?createDatabaseIfNotExist=true&serverTimezone=UTC&&useSSL=false&allowPublicKeyRetrieval=true
        username: lawtask
        password: lawtask@23
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect 
                formate_sql : true 
    servlet:
        multipart:
                max-file-size: 20MB
                max-request-size: 20MB
        
server:  
    port: 8081
    servlet:
        context-path: /api/v1
        
logging:
    level:
        root: INFO
