spring:
    application:
            name: PNC
    datasource:
        url: jdbc:mysql://localhost:3306/PNC?createDatabaseIfNotExist=true&serverTimezone=UTC&&useSSL=false&allowPublicKeyRetrieval=true
        username: lawtask
        password: lawtask@23
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect 
                formate_sql : true 
    servlet:
        multipart:
                max-file-size: 20MB
                max-request-size: 20MB
        
server:  
    port: 8081
    servlet:
        context-path: /api/v1
        
logging:
    level:
        root: INFO

# custom variables

web:
    domain : http://localhost:4200

stripe:
    webhook: whsec_dab51112fcb3a579d7ecd42b56f103c1fbbe197877caf3a2b810c7d76f4d14b4
    secert: sk_test_51N7ejkIjEpaQ2NJZFsDwXUbo3zMECQjLqG3W8vycxbzv3AmFAYGlnYHS1G3PxnOTr1KSkCv7M1MWLxGjB9X0yg8v0062kXo6aZ
    product:
        stall: price_1NhZSdIjEpaQ2NJZy1b56phx
        bazaar: price_1NhZTCIjEpaQ2NJZnMjAEcfG
        elite: price_1NhZU4IjEpaQ2NJZuAnxDFZx
