name: PNC 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - name: Create log directory on Droplet
      run: |
        ssh root@139.59.215.241 'mkdir -p /project1/logs/pnc'

    # Add steps to deploy the application to DigitalOcean droplet
    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Copy JAR to Droplet
      run: scp target/your-project.jar user@your-droplet-ip:/path/to/destination

    - name: Connect to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: 139.59.215.241
        username: root
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /project1
          ./stop.sh
          cd PNC_BACKEND
          mv target/marketplace-0.0.1-SNAPSHOT.jar /project1/marketplace-0.0.1-SNAPSHOT.jar.bak
          cd ..
          ./start.sh
