name: PNC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Droplet
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          source: "target/your-spring-boot-app.jar"
          target: "/path/to/your/droplet/app-new.jar"

      - name: SSH into Droplet and restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop your-app-service
            sudo mv /path/to/your/droplet/app.jar /path/to/your/droplet/app-last.jar
            sudo mv /path/to/your/droplet/app-new.jar /path/to/your/droplet/app.jar
            sudo systemctl start your-app-service
