name: PNC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Droplet and perform tasks
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: 'lawtask'
          script: |
            # Go to the directory and stop the jar application
            cd /project1
            ./stop.sh

            # Go to the directory where the repository is located
            cd /project1/PNC_BACKEND

            # Update the local repository with the latest changes from the remote
            git pull

            # Build the project with Maven
            mvn clean install

            # Start the service again
            cd ..
            ./start.sh
