name: PNC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: 'lawtask'
          script: |
            echo "Connected to Droplet"

      - name: Pull the Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: 'lawtask'
          script: |
            cd /project1/PNC_BACKEND
            git pull
            echo "Repo pulled successfully"

      - name: Build with Maven
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: 'lawtask'
          script: |
            cd /project1/PNC_BACKEND
            mvn clean install
            echo "Build completed successfully"

      - name: Start the Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: 'lawtask'
          script: |
            cd /project1
            ./stop.sh
            cd /project1/PNC_BACKEND
            ./start.sh
            echo "Application started successfully"

      - name: Confirmation Message
        run: echo "All tasks completed successfully"
